### ISSUE TITLE
Error in travis when downgrading conda from 4.4.10 to 4.3

### ISSUE THREAD

**Issue by pradal** [StatisKit/travis-ci#3]
The error is:
```
PS1="$PS1" $_CONDA_EXE shell.posix reactivate
usage: conda [-h] [-V] command ...
conda: error: argument command: invalid choice: u'/home/travis/miniconda/bin/conda' (choose from u'info', u'help', u'list', u'search', u'create', u'install', u'update', u'upgrade', u'remove', u'uninstall', u'config', u'clean', u'package')

```
It seems to be related to this issue (conda >= 4.4):
https://github.com/direnv/direnv/issues/326

**Comment by pfernique** [comment]
Forcing conda, conda-build and anaconda-client versions was necessary in December, 2017.
Perhaps, we should now use the latest versions.
If I remember, the problem with:
* conda and conda-build was that respective commands could not be used in batch scripts (it is therefore more related to the repository https://github.com/StatisKit/appveyor-ci but I prefered to keep same versions for both repositories).
* anaconda-client was that it was not possible to upload packages on a organization if there was no initial file.

I was in a hurry to join the christmas dinner so I didn't raise an issue.
My bad, I don't know if problems were solved...

**Comment by pradal** [comment]
NO problem. I just notice that travis do not work anymore. So we have to found a solution.

**Comment by pfernique** [comment]
OK, did you try to remove versions or do you want me to try (It will perhaps be more easy for me to modify) ?

**Comment by pradal** [comment]
I prefer that you try because I do not know where the problem lie.
Tks

**Comment by pfernique** [comment]
Ok, I first try on StatisKit, then merge in OpenAlea

**Comment by pfernique** [comment]
Here is the issue concerning windows scripts https://github.com/conda/conda/issues/6553.
The issue is closed, but the problem not resolved.
Nevertheless, as mentioned, if all `conda install` are replaced by `conda.exe instal`, its working.
Oddly enough, it seems that you don't need to replace `conda build` by `conda.exe build`.

**Comment by pfernique** [comment]
Travis CI seems to work but I need to finish with AppVeyor CI before pushing modifications to OpenAlea

**Comment by pfernique** [comment]
Everything should be fine now. One can uncomment lines with CONDA_PIN, CONDA_BUILD_PIN and ANACONDA_CLIENT_PIN to revert to previous versions or to force new versions

**Comment by pradal** [comment]
While I have set CONDA=2, my package is built with python3.
See: https://travis-ci.org/openalea/core/jobs/347360455

**Comment by pfernique** [comment]
I can't reproduce this behavior with any of my packages and the `PYTHON_VERSION` variable (used in `conda build --python=$PYTHON_VERSION`) is correctly set.
I think it is due to the fact that `python` is missing in the build dependencies of your package.
For any package that needs python features, I always set `python` as build and run dependencies.
